name: upstream
description: Streaming content discovery web app with torrent integration.
version: 2.0.0

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  path: ^1.8.3
  intl: ^0.18.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  shelf_cors_headers: ^0.1.5
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.12.0

dev_dependencies:
  lints: ^3.0.0

executables:
  server: server
